name: bot

on:
  schedule:
    - cron: "30 * * * *" # every 30 minutes

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE: ${{ secrets.SITE}}
      TOKEN: ${{secrets.TOKEN}}
      CHAT_ID: ${{secrets.CHAT_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm start
